defaults:
  - _self_
  - model: ${oc.decode:${oc.env:MODEL_SIZE,671b}}
  - data_prefix@data.data_prefix: benchmark_c4
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: '.'
  output_subdir: null


trainer:
  devices: ${oc.decode:${oc.env:DGXNGPU,8}}
  num_nodes: ${oc.decode:${oc.env:DGXNNODES,1}}
  max_steps: ${oc.decode:${oc.env:MAX_STEPS,${ceil_div:1382400000,${model.global_batch_size}}}}
  log_every_n_steps: ${oc.decode:${oc.env:LOG_EVERY_N_STEPS,1}}

  val_check_interval: ${oc.decode:${oc.env:VAL_CHECK_INTERVAL,${ceil_div:24576,${model.global_batch_size}}}}
  limit_val_batches: ${oc.decode:${oc.env:LIMIT_VAL_BATCHES,${ceil_div:${oc.decode:${oc.env:VAL_SAMPLES,6144}},${model.global_batch_size}}}}
  eval_batch_size: ${oc.decode:${oc.env:EVAL_BATCH_SIZE,${min:1024,${model.global_batch_size}}}}  # limit validation to at most 1024 samples per batch

  warmup_train_steps: ${oc.decode:${oc.env:WARMUP_TRAIN_STEPS,-1}}
  warmup_validation_steps: ${oc.decode:${oc.env:WARMUP_VALIDATION_STEPS,-1}}

data:
  dataset: ${oc.decode:${oc.env:DATASET,8b}}
  num_workers: 8
  dataloader_type: "single"
  path_to_cache: "/npy_index"
  reset_position_ids: False
  reset_attention_mask: False
  eod_mask_loss: False

optim:
  lr: ${oc.decode:${oc.env:LR,3e-4}}
  min_lr: ${oc.decode:${oc.env:MIN_LR,5e-6}}
  use_precision_aware_optimizer: ${oc.decode:${oc.env:USE_PRECISION_AWARE_OPTIMIZER, True}}
  adam_eps: ${oc.decode:${oc.env:ADAM_EPS,1e-8}}
  sched:
    lr_warmup_iters: ${oc.decode:${oc.env:LR_WARMUP_ITERS,0}}
    lr_decay_iters: ${oc.decode:${oc.env:LR_DECAY_ITERS,11996}}
  overlap_grad_reduce: ${oc.decode:${oc.env:OVERLAP_GRAD_REDUCE,True}}
  overlap_param_gather: ${oc.decode:${oc.env:OVERLAP_PARAM_GATHER,True}}
  align_param_gather:  ${oc.decode:${oc.env:ALIGN_PARAM_GATHER,False}}
  use_distributed_optimizer: ${oc.decode:${oc.env:USE_DIST_OPTIMIZER,True}}
  bucket_size: ${oc.decode:${oc.env:BUCKET_SIZE,134217728}}
  fp8_param_gather: ${oc.decode:${oc.env:FP8_PARAM_GATHER,False}}
  fp4_param_gather: ${oc.decode:${oc.env:FP4_PARAM_GATHER,False}}
  reuse_grad_buf_for_mxfp8_param_ag: ${oc.decode:${oc.env:REUSE_GRAD_BUF_FOR_MXFP8_PARAM_AG,False}}
  num_distributed_optimizer_instances: ${oc.decode:${oc.env:NUM_DISTOPT_INSTANCES,1}}
  outer_dp_sharding_strategy: ${oc.decode:${oc.env:OUTER_DP_SHARDING_STRATEGY,no_shard}}
  nccl_ub_dp: ${oc.decode:${oc.env:NCCL_UB_DP,False}}
  overlap_param_gather_with_optim_step: ${oc.decode:${oc.env:OVERLAP_PARAM_GATHER_WITH_OPTIM_STEP,False}}

  # If true, manually register the FSDP communication buffers to NCCL user buffer.
  # This option is only effective when use_megatron_fsdp and nccl_ub is set.
  # For symmetric registration with large models, the registration itself can take
  # a significant amount of time. This option minimizes the number of registration calls
  # to minimize the registration time.
  fsdp_manual_registration: ${oc.decode:${oc.env:FSDP_MANUAL_REGISTRATION,False}}
  optimizer_cuda_graph: ${oc.decode:${oc.env:OPTIMIZER_CG, False}}
  on_device_clip_grad: ${oc.decode:${oc.env:ON_DEVICE_CLIP_GRAD, False}}

# TODO(dfridman): the below arguments are needed to silence run_and_time.sh errors
# revisit when enabling checkpointing
exp_manager:
  explicit_log_dir: '/results'
  load_optim: ${oc.decode:${oc.env:LOAD_OPTIMIZER,False}}
  load_rng_state: ${oc.decode:${oc.env:LOAD_RNG_STATE,False}}
  save_optim: ${oc.decode:${oc.env:SAVE_OPTIMIZER,False}}
  save_rng_state: ${oc.decode:${oc.env:SAVE_RNG_STATE,False}}
  # TODO(dfridman): debug async_save=True. Logs(prenyx): `/lustre/fsw/coreai_mlperf_training/users/dfridman/logs/dsv3-megatron-bridge/6/slurm-1234361.out` 
  async_save: False
  save_interval: ${oc.decode:${oc.env:CHECKPOINT_SAVE_INTERVAL,-1}}  # if negative, do not save
  most_recent_k: ${oc.decode:${oc.env:CHECKPOINT_MOST_RECENT_K,1}}
  # Base dir (mounted at /checkpoints); LOAD_CHECKPOINT is the container path to load from (e.g. /checkpoints/mbridge-ckpt)
  load_checkpoints_dir: ${oc.env:LOAD_CHECKPOINTS_DIR,null}
  load_checkpoint: ${oc.env:LOAD_CHECKPOINT,/checkpoints}
  load_checkpoint_step: ${oc.decode:${oc.env:LOAD_CHECKPOINT_STEP,null}}  # specifies, which checkpoint to load; by default, load the latest checkpoint

custom:
  force_success_status: ${oc.decode:${oc.env:FORCE_SUCCESS_STATUS,0}} # If True, sets the MLLOG status to SUCCESS at run_stop even if target accuracy was not reached so the dryrun report parsing works
  target_log_ppl: ${oc.decode:${oc.env:TARGET_LOG_PPL,3.6}}
