apiVersion: kubeflow.org/v1
kind: MPIJob
metadata:
  name: llama31-8b-n8-mpijob
  namespace: default
spec:
  slotsPerWorker: 8
  runPolicy:
    cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                    - controlplane001
          tolerations:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
            effect: NoSchedule
          - key: node-role.kubernetes.io/master
            operator: Exists
            effect: NoSchedule
          - key: node.kubernetes.io/unschedulable
            operator: Exists
            effect: NoSchedule
          containers:
          - name: main
            image: registry-ap-southeast.scitix.ai/k8s/mlperf-nvidia:llama31_8b-pyt
            imagePullPolicy: Always
            command: ["/usr/bin/env", "bash", "-c"]
            args: ["sleep inf"]
            env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: TZ
              value: CST-8
            - name: NCCL_DEBUG
              value: WARN
            - name: NCCL_ASYNC_ERROR_HANDLING
              value: "1"
            - name: NCCL_SOCKET_IFNAME
              value: eth0
            - name: GLOO_SOCKET_IFNAME
              value: eth0
            volumeMounts:
            - mountPath: /dev/shm
              name: shm
            - mountPath: /data/mlperf_training
              name: training
            - name: code
              mountPath: /workspace/ft-llm-shared
            workingDir: /workspace/ft-llm-shared
          volumes:
          - name: shm
            emptyDir:
              medium: Memory
          - name: training
            hostPath:
              path: /mnt/xstorage/mlperf_runs
              type: Directory
          - name: code
            hostPath:
              path: /mnt/xstorage/ft-llm-8b
              type: Directory

    Worker:
      replicas: 8
      template:
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                    - gpu-10-220-55-10
                    - gpu-10-220-55-11
                    - gpu-10-220-55-12
                    - gpu-10-220-55-13
                    - gpu-10-220-55-14
                    - gpu-10-220-55-7
                    - gpu-10-220-55-8
                    - gpu-10-220-55-9
          tolerations:
          - key: scitix.ai/nodecheck
            operator: Exists
            effect: NoSchedule
          - key: node.kubernetes.io/unschedulable
            operator: Exists
            effect: NoSchedule
          - key: nvidia.com/gpu
            operator: Exists
            effect: NoSchedule
          containers:
          - name: main
            image: registry-ap-southeast.scitix.ai/k8s/mlperf-nvidia:llama31_8b-pyt
            imagePullPolicy: Always
            env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: TZ
              value: CST-8
            - name: NCCL_DEBUG
              value: WARN
            - name: NCCL_ASYNC_ERROR_HANDLING
              value: "1"
            - name: NCCL_SOCKET_IFNAME
              value: eth0
            - name: GLOO_SOCKET_IFNAME
              value: eth0
            resources:
              requests:
                nvidia.com/gpu: 8
                rdma/hca_shared_devices_all: "2"
              limits:
                nvidia.com/gpu: 8
                rdma/hca_shared_devices_all: "2"
            securityContext:
              capabilities:
                add:
                - IPC_LOCK
            volumeMounts:
            - mountPath: /dev/shm
              name: shm
            - mountPath: /data/8b
              name: dataset
            - mountPath: /data/mlperf_training
              name: training
            - name: code
              mountPath: /workspace/ft-llm-shared
            workingDir: /workspace/ft-llm-shared
          volumes:
          - name: shm
            emptyDir:
              medium: Memory
          - name: dataset
            hostPath:
              path: /mnt/xstorage/8b
              type: Directory
          - name: training
            hostPath:
              path: /mnt/xstorage/mlperf_runs
              type: Directory
          - name: code
            hostPath:
              path: /mnt/xstorage/ft-llm-8b
              type: Directory

